from pynapse.core.constants import SIZE_CONSTANTS, TIME_CONSTANTS

TOKENS = {
    "USDFC": "USDFC",
    "FIL": "FIL",
}

METADATA_KEYS = {
    "WITH_CDN": "withCDN",
    "WITH_IPFS_INDEXING": "withIPFSIndexing",
    "IPFS_ROOT_CID": "ipfsRootCID",
}

TIMING_CONSTANTS = {
    "TRANSACTION_PROPAGATION_TIMEOUT_MS": 180000,
    "TRANSACTION_PROPAGATION_POLL_INTERVAL_MS": 2000,
    "DATA_SET_CREATION_TIMEOUT_MS": 7 * 60 * 1000,
    "DATA_SET_CREATION_POLL_INTERVAL_MS": 2000,
    "PIECE_PARKING_TIMEOUT_MS": 7 * 60 * 1000,
    "PIECE_PARKING_POLL_INTERVAL_MS": 5000,
    "TRANSACTION_CONFIRMATIONS": 1,
    "PERMIT_DEADLINE_DURATION": 3600,
    "PIECE_ADDITION_TIMEOUT_MS": 7 * 60 * 1000,
    "PIECE_ADDITION_POLL_INTERVAL_MS": 1000,
}
