TIME_CONSTANTS = {
    "EPOCH_DURATION": 30,
    "EPOCHS_PER_DAY": 2880,
    "EPOCHS_PER_MONTH": 86400,
    "DAYS_PER_MONTH": 30,
    "DEFAULT_LOCKUP_DAYS": 30,
}

SIZE_CONSTANTS = {
    "KiB": 1024,
    "MiB": 1 << 20,
    "GiB": 1 << 30,
    "TiB": 1 << 40,
    "PiB": 1 << 50,
    "MAX_UPLOAD_SIZE": 1_065_353_216,
    "MIN_UPLOAD_SIZE": 127,
    "DEFAULT_UPLOAD_BATCH_SIZE": 32,
}

LOCKUP_PERIOD = TIME_CONSTANTS["DEFAULT_LOCKUP_DAYS"] * TIME_CONSTANTS["EPOCHS_PER_DAY"]

RETRY_CONSTANTS = {
    "FACTOR": 1,
    "DELAY_TIME": 4000,
    "RETRIES": None,
    "MAX_RETRY_TIME": 1000 * 60 * 5,
}
